default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate

development:
  primary:
    <<: *default
    database: mtasks_development
  # cache:
  #   <<: *cache
  #   database: myapp_development_cache
  queue:
    <<: *queue
    database: mtasks_dev_queue
  cable:
    <<: *default
    database: mtasks_dev_cable
    migrations_paths: db/cable_migrate
test:
  <<: *default
  database: mtasks_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    url: <%= ENV['BLUE_DATABASE_URL'] %>
    # migrations_paths: db/cache_migrate
  queue:
    <<: *queue
    url: <%= ENV['DATABASE_QUEUE_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_CABLE_URL'] %>
    migrations_paths: db/cable_migrate
